language: python

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.6
    env: TOXENV=docs
  - python: 3.6
    env: TOXENV=lint,style
  - python: nightly
  fast_finish: true
  allow_failures:
  - python: 3.7  # Travis doesn't seem to support 3.7 yet...
  - python: nightly
  - python: 3.6
    env: TOXENV=lint,style
env:
  global:
    - TOXENV: py

env:
  global:
  - TOXENV=py-coverage
  - PYTEST_ADDOPTS="--e2e-engine=local --e2e-tester=unittest --e2e-tester=pytest"

install:
- pip install tox

services: rabbitmq

# before_script:
#  - pushd test/test_project
#  - celery -A cosmic_ray_celery3_engine.worker worker &
#  - celery -A cosmic_ray_celery4_engine.worker worker --concurrency=1 --purge &
#  - popd

script:
- tox

after_success:
- |
  pip install codecov
  coverage xml
  codecov_flags=py${TRAVIS_PYTHON_VERSION//./}
  codecov --required -X search gcov pycov -f coverage.xml --flags $codecov_flags

# When we push to 'release', the python-3.6 travis run should do a deployment.
deploy:
  provider: pypi
  user: abingham
  password:
    secure: ckgurny6GwdI4Ya7FtyP536v11ynyc3uUgjUjQPANtXf8duyB57dKN28UJQ2CcpDHNRCaJPVsZZBgIARwnbSozEgDKiZk7Ng13dU/tHZ9bkMcFPvQMLwCv5JTG33M0dn9SEzoV5YZT0ro35zC+VDJFOO7yvX1cb2WiMLTcudV9A=
  distributions: bdist_wheel sdist
  on:
    branch: release
    python: 3.6

before_deploy:
- openssl aes-256-cbc -K $encrypted_6ad9c4041ffc_key -iv $encrypted_6ad9c4041ffc_iv -in deploy_key.enc -out deploy_key -d
- python scripts/make_release_tag.py
